# Generated by Django 5.2.14 on 2026-05-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(blank=True, max_length=200, verbose_name='العنوان بالعربي')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='العنوان بالإنجليزي')),
                ('image', models.ImageField(upload_to='banner/', verbose_name='الصورة')),
                ('link', models.URLField(blank=True, verbose_name='الرابط عند الضغط')),
                ('position', models.CharField(choices=[('hero', 'السلايدر الرئيسي'), ('secondary', 'بانر ثانوي'), ('popup', 'نافذة منبثقة')], default='hero', max_length=15, verbose_name='الموضع')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'بانر',
                'verbose_name_plural': 'البانرات',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
