# Generated by Django 5.2.14 on 2026-05-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='+201069545469', max_length=30, verbose_name='رقم الهاتف')),
                ('logo_text', models.CharField(default='MAV', max_length=30, verbose_name='نص اللوجو')),
                ('logo_accent', models.CharField(default='A', max_length=5, verbose_name='الحرف المميز في اللوجو')),
                ('show_top_bar', models.BooleanField(default=True, verbose_name='إظهار الشريط العلوي')),
                ('show_phone', models.BooleanField(default=True, verbose_name='إظهار رقم الهاتف')),
                ('show_language_switcher', models.BooleanField(default=True, verbose_name='إظهار اختيار اللغة')),
                ('show_search', models.BooleanField(default=True, verbose_name='إظهار البحث')),
                ('show_wishlist', models.BooleanField(default=True, verbose_name='إظهار المفضلة')),
                ('show_cart', models.BooleanField(default=True, verbose_name='إظهار السلة')),
                ('search_placeholder_ar', models.CharField(default='ابحث عن العطر...', max_length=100, verbose_name='نص البحث بالعربي')),
                ('search_placeholder_en', models.CharField(default='Search perfumes...', max_length=100, verbose_name='نص البحث بالإنجليزي')),
                ('mobile_search_placeholder_ar', models.CharField(default='ابحث...', max_length=100, verbose_name='نص بحث الموبايل بالعربي')),
                ('mobile_search_placeholder_en', models.CharField(default='Search...', max_length=100, verbose_name='نص بحث الموبايل بالإنجليزي')),
                ('show_home_link', models.BooleanField(default=True, verbose_name='إظهار الرئيسية')),
                ('home_label_ar', models.CharField(default='الرئيسية', max_length=50, verbose_name='عنوان الرئيسية بالعربي')),
                ('home_label_en', models.CharField(default='Home', max_length=50, verbose_name='عنوان الرئيسية بالإنجليزي')),
                ('show_categories_link', models.BooleanField(default=True, verbose_name='إظهار الفئات')),
                ('categories_label_ar', models.CharField(default='الفئات', max_length=50, verbose_name='عنوان الفئات بالعربي')),
                ('categories_label_en', models.CharField(default='Categories', max_length=50, verbose_name='عنوان الفئات بالإنجليزي')),
                ('categories_menu_title_ar', models.CharField(default='تصفح حسب الفئة', max_length=80, verbose_name='عنوان قائمة الفئات بالعربي')),
                ('categories_menu_title_en', models.CharField(default='Browse by Category', max_length=80, verbose_name='عنوان قائمة الفئات بالإنجليزي')),
                ('show_offers_link', models.BooleanField(default=True, verbose_name='إظهار العروض')),
                ('offers_label_ar', models.CharField(default='العروض', max_length=50, verbose_name='عنوان العروض بالعربي')),
                ('offers_label_en', models.CharField(default='Offers', max_length=50, verbose_name='عنوان العروض بالإنجليزي')),
                ('show_brands_link', models.BooleanField(default=True, verbose_name='إظهار الماركات')),
                ('brands_label_ar', models.CharField(default='الماركات', max_length=50, verbose_name='عنوان الماركات بالعربي')),
                ('brands_label_en', models.CharField(default='Brands', max_length=50, verbose_name='عنوان الماركات بالإنجليزي')),
                ('show_track_order_link', models.BooleanField(default=True, verbose_name='إظهار تتبع الطلب')),
                ('track_order_label_ar', models.CharField(default='تتبع الطلب', max_length=50, verbose_name='عنوان تتبع الطلب بالعربي')),
                ('track_order_label_en', models.CharField(default='Track Order', max_length=50, verbose_name='عنوان تتبع الطلب بالإنجليزي')),
                ('show_about_link', models.BooleanField(default=True, verbose_name='إظهار من نحن')),
                ('about_label_ar', models.CharField(default='من نحن', max_length=50, verbose_name='عنوان من نحن بالعربي')),
                ('about_label_en', models.CharField(default='About', max_length=50, verbose_name='عنوان من نحن بالإنجليزي')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات الهيدر',
                'verbose_name_plural': 'إعدادات الهيدر',
            },
        ),
    ]
