# Generated by Django 5.2.14 on 2026-05-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_text', models.CharField(default='MAV', max_length=30, verbose_name='نص اللوجو (الفوتر)')),
                ('logo_accent', models.CharField(default='A', max_length=5, verbose_name='الحرف المميز (الفوتر)')),
                ('tagline_ar', models.CharField(default='عطور فاخرة — منذ ٢٠٢٠', max_length=100, verbose_name='النص التعريفي القصير بالعربي')),
                ('tagline_en', models.CharField(default='Luxury Perfumes — Est. 2020', max_length=100, verbose_name='النص التعريفي القصير بالإنجليزي')),
                ('about_text_ar', models.TextField(default='اكتشف مجموعتنا المختارة من العطور الفاخرة من حول العالم.', verbose_name='عن المتجر بالعربي')),
                ('about_text_en', models.TextField(default='Discover our curated collection of luxury fragrances from around the world.', verbose_name='عن المتجر بالإنجليزي')),
                ('fb_link', models.URLField(blank=True, null=True, verbose_name='رابط فيسبوك')),
                ('insta_link', models.URLField(blank=True, null=True, verbose_name='رابط إنستجرام')),
                ('wa_link', models.CharField(default='201069545469', max_length=100, verbose_name='رابط/رقم واتساب')),
                ('tiktok_link', models.URLField(blank=True, null=True, verbose_name='رابط تيك توك')),
                ('phone', models.CharField(default='+201069545469', max_length=30, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(default='info@mavaperfumes.com', max_length=254, verbose_name='البريد الإلكتروني')),
                ('working_hours_ar', models.CharField(default='السبت – الخميس: ١٠ص – ١٠م', max_length=100, verbose_name='ساعات العمل بالعربي')),
                ('working_hours_en', models.CharField(default='Sat – Thu: 10am – 10pm', max_length=100, verbose_name='ساعات العمل بالإنجليزي')),
                ('address_ar', models.CharField(default='مصر', max_length=200, verbose_name='العنوان بالعربي')),
                ('address_en', models.CharField(default='Egypt', max_length=200, verbose_name='العنوان بالإنجليزي')),
                ('copyright_text_ar', models.CharField(default='© 2025 مافا للعطور. جميع الحقوق محفوظة.', max_length=200, verbose_name='نص حقوق النشر بالعربي')),
                ('copyright_text_en', models.CharField(default='© 2025 MAVA Perfumes. All rights reserved.', max_length=200, verbose_name='نص حقوق النشر بالإنجليزي')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات الفوتر',
                'verbose_name_plural': 'إعدادات الفوتر',
            },
        ),
        migrations.AddField(
            model_name='headersettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='الأيقونة (Favicon)'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='صورة اللوجو'),
        ),
    ]
