# Generated by Django 5.2.14 on 2026-05-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_footersettings_headersettings_favicon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='صورة اللوجو (الفوتر)'),
        ),
    ]
