# Generated by Django 5.2.14 on 2026-05-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_footersettings_logo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='messenger_link',
            field=models.URLField(blank=True, null=True, verbose_name='رابط ماسنجر'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='wa_link',
            field=models.CharField(default='201069545469', max_length=100, verbose_name='رقم واتساب (بدون +)'),
        ),
    ]
