# Generated by Django 5.2.14 on 2026-05-06 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('first_name', models.CharField(max_length=50, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=50, verbose_name='الاسم الأخير')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='customer/avatars/', verbose_name='الصورة الشخصية')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('governorate', models.CharField(choices=[('cairo', 'القاهرة'), ('giza', 'الجيزة'), ('alexandria', 'الإسكندرية'), ('luxor', 'الأقصر'), ('aswan', 'أسوان'), ('port_said', 'بورسعيد'), ('suez', 'السويس'), ('mansoura', 'المنصورة'), ('tanta', 'طنطا'), ('zagazig', 'الزقازيق'), ('ismailia', 'الإسماعيلية'), ('fayoum', 'الفيوم'), ('minya', 'المنيا'), ('asyut', 'أسيوط'), ('sohag', 'سوهاج'), ('qena', 'قنا'), ('beni_suef', 'بني سويف'), ('dakahlia', 'الدقهلية'), ('sharqia', 'الشرقية'), ('gharbia', 'الغربية'), ('kafr_el_sheikh', 'كفر الشيخ'), ('beheira', 'البحيرة'), ('monufia', 'المنوفية'), ('qalyubia', 'القليوبية'), ('damietta', 'دمياط'), ('north_sinai', 'شمال سيناء'), ('south_sinai', 'جنوب سيناء'), ('red_sea', 'البحر الأحمر'), ('matrouh', 'مطروح'), ('new_valley', 'الوادي الجديد')], max_length=50, verbose_name='المحافظة')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة / الحي')),
                ('street', models.CharField(max_length=255, verbose_name='الشارع')),
                ('building', models.CharField(blank=True, max_length=50, verbose_name='رقم المبنى / الشقة')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='الرمز البريدي')),
                ('is_default', models.BooleanField(default=False, verbose_name='العنوان الافتراضي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'عنوان',
                'verbose_name_plural': 'العناوين',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
