# Generated by Django 5.2.14 on 2026-05-06 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='المدينة بالعربي')),
                ('name_en', models.CharField(max_length=100, verbose_name='المدينة بالإنجليزي')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تكلفة الشحن')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مدينة',
                'verbose_name_plural': 'المدن',
                'ordering': ['governorate', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='المحافظة بالعربي')),
                ('name_en', models.CharField(max_length=100, verbose_name='المحافظة بالإنجليزي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'محافظة',
                'verbose_name_plural': 'المحافظات',
                'ordering': ['name_ar'],
            },
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='accounts.city', verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='city',
            name='governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='accounts.governorate', verbose_name='المحافظة'),
        ),
        migrations.AlterField(
            model_name='address',
            name='governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='accounts.governorate', verbose_name='المحافظة'),
        ),
    ]
