# Generated by Django 6.0.3 on 2026-05-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_city_governorate_alter_address_city_city_governorate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.CharField(choices=[('admin', 'مدير النظام'), ('manager', 'مدير'), ('supervisor', 'مشرف'), ('employee', 'موظف'), ('customer', 'عميل')], default='customer', max_length=20, verbose_name='الصلاحية'),
        ),
    ]
