# Generated by Django 6.0.3 on 2026-05-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='has_whatsapp',
            field=models.BooleanField(default=False, verbose_name='رقم الهاتف به واتساب؟'),
        ),
    ]
