# Generated by Django 5.2.14 on 2026-05-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customer_has_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='role',
            field=models.CharField(choices=[('admin', 'مدير النظام'), ('manager', 'المدير'), ('supervisor', 'المشرف'), ('employee', 'الموظف'), ('accountant', 'المحاسب'), ('customer', 'عميل')], default='customer', max_length=20, verbose_name='الصلاحية'),
        ),
    ]
