# Generated by Django 5.2.14 on 2026-05-06 13:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('count_1_star', models.PositiveIntegerField(default=0)),
                ('count_2_star', models.PositiveIntegerField(default=0)),
                ('count_3_star', models.PositiveIntegerField(default=0)),
                ('count_4_star', models.PositiveIntegerField(default=0)),
                ('count_5_star', models.PositiveIntegerField(default=0)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_summary', to='products.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'ملخص تقييمات',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '⭐ ضعيف'), (2, '⭐⭐ مقبول'), (3, '⭐⭐⭐ جيد'), (4, '⭐⭐⭐⭐ جيد جداً'), (5, '⭐⭐⭐⭐⭐ ممتاز')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='عنوان التقييم')),
                ('comment', models.TextField(blank=True, verbose_name='التعليق')),
                ('is_approved', models.BooleanField(default=True, verbose_name='معتمد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'تقييم',
                'verbose_name_plural': 'التقييمات',
                'ordering': ['-created_at'],
                'unique_together': {('product', 'customer')},
            },
        ),
    ]
