# Generated by Django 5.2.14 on 2026-05-06 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='رقم الطلب')),
                ('shipping_full_name', models.CharField(max_length=100, verbose_name='اسم المستلم')),
                ('shipping_phone', models.CharField(max_length=20, verbose_name='هاتف المستلم')),
                ('shipping_governorate', models.CharField(max_length=100, verbose_name='المحافظة')),
                ('shipping_city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('shipping_street', models.CharField(max_length=255, verbose_name='الشارع')),
                ('shipping_building', models.CharField(blank=True, max_length=50, verbose_name='المبنى / الشقة')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المجموع الجزئي')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تكلفة الشحن')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قيمة الخصم')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الإجمالي')),
                ('payment_method', models.CharField(choices=[('cod', 'الدفع عند الاستلام'), ('card', 'بطاقة إلكترونية'), ('wallet', 'محفظة إلكترونية')], default='cod', max_length=10, verbose_name='طريقة الدفع')),
                ('is_paid', models.BooleanField(default=False, verbose_name='تم الدفع')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الدفع')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'قيد المعالجة'), ('shipped', 'تم الشحن'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغي'), ('refunded', 'مُسترد')], default='pending', max_length=15, verbose_name='حالة الطلب')),
                ('coupon_code', models.CharField(blank=True, max_length=50, verbose_name='كود الخصم')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات العميل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='اسم المنتج')),
                ('product_sku', models.CharField(max_length=20, verbose_name='كود المنتج')),
                ('product_image', models.CharField(blank=True, max_length=500, verbose_name='صورة المنتج')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='الكمية')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='الطلب')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'عنصر في الطلب',
                'verbose_name_plural': 'عناصر الطلبات',
            },
        ),
    ]
