# Generated by Django 6.0.3 on 2026-05-07 13:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود الكوبون')),
                ('valid_from', models.DateTimeField(verbose_name='صالح من')),
                ('valid_to', models.DateTimeField(verbose_name='صالح إلى')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الخصم (%)')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'كوبون',
                'verbose_name_plural': 'الكوبونات',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='orders.coupon', verbose_name='الكوبون'),
        ),
    ]
