# Generated by Django 5.2.14 on 2026-05-09 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_coupon_created_at_coupon_updated_at'),
        ('products', '0002_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=200, verbose_name='اسم العرض بالعربي')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='اسم العرض بالإنجليزي')),
                ('description', models.TextField(blank=True, verbose_name='وصف العرض')),
                ('offer_type', models.CharField(choices=[('bogo', 'اشتري X وخذ Y مجاناً'), ('percentage', 'خصم نسبة مئوية'), ('quantity', 'خصم عند شراء كمية معينة'), ('free_shipping', 'شحن مجاني')], max_length=20, verbose_name='نوع العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('valid_from', models.DateTimeField(verbose_name='يبدأ من')),
                ('valid_to', models.DateTimeField(verbose_name='ينتهي في')),
                ('apply_to_all', models.BooleanField(default=False, verbose_name='ينطبق على كل المنتجات')),
                ('buy_quantity', models.PositiveIntegerField(default=2, verbose_name='اشتري كمية')),
                ('get_quantity', models.PositiveIntegerField(default=1, verbose_name='احصل على كمية مجاناً')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الخصم %')),
                ('min_quantity', models.PositiveIntegerField(default=1, verbose_name='الحد الأدنى للكمية')),
                ('quantity_discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة خصم الكمية %')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الحد الأدنى لمبلغ الطلب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eligible_categories', models.ManyToManyField(blank=True, related_name='offers', to='products.category', verbose_name='الفئات')),
                ('eligible_products', models.ManyToManyField(blank=True, related_name='offers', to='products.product', verbose_name='المنتجات')),
                ('free_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_in_offers', to='products.product', verbose_name='المنتج المجاني (فارغ = نفس المنتج)')),
            ],
            options={
                'verbose_name': 'عرض',
                'verbose_name_plural': 'العروض',
                'ordering': ['-created_at'],
            },
        ),
    ]
