# Generated by Django 5.2.14 on 2026-06-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_brand_slug_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='concentration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='التركيز'),
        ),
    ]
