# Generated by Django 5.2.14 on 2026-07-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_concentration'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_box',
            field=models.BooleanField(default=True, verbose_name='بعلبة'),
        ),
    ]
